### ISSUE TITLE
Create tests for all the API endpoints

### ISSUE THREAD

**Issue by gigili** [gigili/good-food-tracker-api#43]
There should be tests created for all the API routes.

Some resources for it:

[Testing ExpressJS REST API with Mocha and Chai | Medium](https://medium.com/kanssfer-consulting/testing-expressjs-rest-api-with-mocha-and-chai-90bf4178f15e)
[How to Test Nodejs Code and RESTful API | CodeForGeek](https://codeforgeek.com/unit-testing-nodejs-application-using-mocha/)
[Testing NodeJs/Express API with Jest and Supertest | Dev.to](https://dev.to/nedsoft/testing-nodejs-express-api-with-jest-and-supertest-1km6)
[Mocking ExpressJS Request and Response objects | ITNEXT](https://itnext.io/mocking-expressjs-request-and-response-objects-63405e9c58ff)

**Comment by thiagojmlins** [comment]
I'd like to pick this up.

**Comment by gigili** [comment]
Hey,

thank you for taking an interest, your help would be much appreciated :)

**Comment by thiagojmlins** [comment]
No problem, I hope to be helpful :)

**Comment by gigili** [comment]
One thing I'd like to note as I'm not sure if it obvious from the code itself is that almost all routes expect the guid to be sent and not the numerical id as a parameter for the request. 

Some routes such as those for the city and/or country use the numerical ID.

**Comment by thiagojmlins** [comment]
I'm having a problem trying to run migrations. I have setup the MySQL DB, but every time I try to run the `db-migrate up`, it returns me this error:

`received data: CREATE TABLE `user` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL ,
    email VARCHAR(100) NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    active ENUM('0','1') NOT NULL DEFAULT '0',
    created_at DATE DEFAULT CURRENT_DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `user`
    (name, email, username, password, active)
VALUES
    ('Igor Ilić', 'igorilicbl@gmail.com', 'gac', 'fac5b2c9d9fe1d6cc567798868a6e02124a50f4d3d4330ea96a95ddb62e9673b', '1');
[ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CURRENT_DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `user`
    (n' at line 8
    at Query.Sequence._packetToError (/home/thiago/Code/good-food-tracker-api/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/thiago/Code/good-food-tracker-api/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/thiago/Code/good-food-tracker-api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/thiago/Code/good-food-tracker-api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/thiago/Code/good-food-tracker-api/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/thiago/Code/good-food-tracker-api/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/thiago/Code/good-food-tracker-api/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/thiago/Code/good-food-tracker-api/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
    --------------------
    at Protocol._enqueue (/home/thiago/Code/good-food-tracker-api/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/thiago/Code/good-food-tracker-api/node_modules/mysql/lib/Connection.js:198:25)
    at /home/thiago/Code/good-food-tracker-api/node_modules/db-migrate-mysql/index.js:450:29
    at Promise._execute (/home/thiago/Code/good-food-tracker-api/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/home/thiago/Code/good-food-tracker-api/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/home/thiago/Code/good-food-tracker-api/node_modules/bluebird/js/release/promise.js:103:10)
    at Object.runSql (/home/thiago/Code/good-food-tracker-api/node_modules/db-migrate-mysql/index.js:445:12)
    at /home/thiago/Code/good-food-tracker-api/migrations/20200829180451-user.js:32:15
    at tryCatcher (/home/thiago/Code/good-food-tracker-api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/thiago/Code/good-food-tracker-api/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/thiago/Code/good-food-tracker-api/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/thiago/Code/good-food-tracker-api/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/thiago/Code/good-food-tracker-api/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/thiago/Code/good-food-tracker-api/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/thiago/Code/good-food-tracker-api/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/thiago/Code/good-food-tracker-api/node_modules/bluebird/js/release/async.js:102:5)`

What am I doing wrong?

**Comment by gigili** [comment]
I've noticed that issue my self when using older versions of MariaDB database < 10.4.6. 
So if you have a MariaDB version above 10.4.6 it should work. But I'll try and create an sql version of the import file that supports older versions. Because older versions of MariaDB don't support some of the syntax in those queries. 

I've successfully imported migrations on versions 10.4.6 and 10.5.5.

**Comment by gigili** [comment]
I've merged the new version of migrations into the main branch which should allow you to run all the migrations without any issues. Do let me know if there are any problems with it.

**Comment by gigili** [comment]
We you able to run the migrations since the new update?

**Comment by thiagojmlins** [comment]
Hi, Igor. Sorry about the delay, these days were exhausting. I've tried to run them after your update, but no luck. Some of the tables didn't update. I'll try another run later today and let you know if I succeed, and if doesn't work, I'll share the output with you.

**Comment by gigili** [comment]
Hey, no worries. I think you will need to delete all the tables first and than run the migrations as I didn't create new ones but rather rewrote the old ones. So it needs to be a clean database for it to succeed. 

I tested it on 10.4.1 without any issues, so now it should be good. 

When you have the time, try and just let me know. If it still throws errors I'll try and update it more.
